INSERT INTO backlog_items
VALUES
 /* ID, Title, Description, Effort, Priority, State, Iteration, Project */
(NULL, 'Content/Site Map', 'Diagram detailing where content goes/Navigational layout of the website', '5', '3', '1', '2', '1'),
(NULL, 'Wireframes', 'Diagrams of structural layout of the website', '5', '3', '1', NULL, '1'),
(NULL, 'Brand Identity Document', 'Document detailing all aspects of coporate branding - Colours, Logos, Fonts', '8', '3', '1', '1', '1'),
(NULL, 'Produce Visual Templated', 'Designs for different pages within the website', '13', '3', '1', NULL, '1'),
(NULL, 'Competitor Critique', 'Comapare different websites that do the same thing and see how we can go one better', '3', '3', '1', NULL, '1'),
(NULL, 'Decide on Web Design Frameworks', 'Decide on a Bootstrap template to use', '2', '3', '1', '2', '1'),
(NULL, 'Edit HTML and CSS inline with Design Work', NULL, '5', '3', '1', NULL, '1'),
(NULL, 'Write PHP', NULL, '13', '3', '1', NULL, '1'),
(NULL, 'Write Json', NULL, '5', '3', '1', NULL, '1'),
(NULL, 'Write JavaScript', NULL, '13', '3', '1', NULL, '1'),
(NULL, 'Write AJAX', NULL, '5', '3', '1', NULL, '1'),
(NULL, 'Add coming soon page', NULL, '3', '3', '1', '1', '1'),
(NULL, 'Bring coming soon page inline with Brand ID Document', NULL, '5', '3', '1', '2', '1'),
(NULL, 'Design and write queries to populate graphs', NULL, '3', '3', '1', NULL, '1'),
(NULL, 'Decide on Project Metrics', 'Be able to show a Release Burndown, multiple burndowns, velocity and an admin page', '1', '3', '1', '1', '1'),
(NULL, 'Research Graphs', 'A look into what makes a good graph and how they should be presented', '3', '3', '1', '2', '1'),
(NULL, 'Redesign Database and create ERD', 'Look at whether we need more tables and create an ERD to reflect the design', '16', '3', '1', '1', '1'),
(NULL, 'Create Physical Data Model', 'Create a data model so that we know what fields attributes are going to have', '5', '3', '1', '1', '1'),
(NULL, 'Write SQL Scripts', 'Write CREATE, ALTER, DROP and INSERT scripts to populate the database', '5', '3', '1', '1', '1'),
(NULL, 'Input data into database using our own data', 'Using our own data insert into database the PBIs, Tasks etc', '8', '3', '1', '2', '1'),
(NULL, 'Populate Database', NULL, '5', '3', '1', NULL, '1'),
(NULL, 'Get Hosting', 'VidaHost', '3', '3', '1', '1', '1'),
(NULL, 'Create PBI Form', 'Pay attention to date formats during creation', NULL, '3', '1', NULL, '1'),
(NULL, 'Create Task Form', 'Project team enter task details here', NULL, '3', '1', NULL, '1'),
(NULL, 'Create Form Validation', 'Enable simple inputs with reduced errors', NULL, '3', '1', NULL, '1'),
(NULL, 'Design The Forms', 'Decide on standard format and design of data entry', NULL, '3', '1', NULL, '1'),
(NULL, 'Plan Nullable Fields', NULL, NULL, '2', '1', '1', '1'),
(NULL, 'Thoroughly go through validation using Test Script', 'Confirm error reduction', NULL, '2', '1', NULL, '1'),
(NULL, 'Trigger for audit table', 'Create automated process', NULL, '2', '1', NULL, '1'),
(NULL, 'Create audit table for changes to PBIs and Tasks', 'Table to show changes made by team', NULL, '2', '1', NULL, '1'),
(NULL, 'Create comments table for PBI', 'Enable team to explain progress/what has been done', '1', '1', '1', '1', '1'),
(NULL, 'Create comments table for tasks', 'enable team to explain progress', '1', '1', '1', '1', '1'),
(NULL, 'Design UI for assigning Effort and Time', 'Decide on drop down menu/sliders', NULL, '3', '1', NULL, '1'),
(NULL, 'Integrate value into database', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Design UI for choosing status', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Choose status', 'decide standard terms', '1', '2', '1', NULL,'1'),
(NULL, 'Integrate with database', 'show changes/choices in database', NULL, '1', '1', NULL, '1'),
(NULL, 'Allow user to choose project that they are a member of', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Create rating system for tasks', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Integrate rating system with database', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Design UI for assigning work', 'Come up with a way to assign work to other group members', NULL, '3', '1', NULL, '1'),
(NULL, 'Send notification when work is assigned to you', 'What type of notification? email etc', NULL, '3', '1', NULL, '1'),
(NULL, 'Send notification when work assigned to you is edited', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Task/PBI creator field in database', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Task/PBI created date', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Task/PBI updated date', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Display one Burndown graph on a page', 'Design page template, build, PHP, JavaScript', NULL, '3', '1', NULL,'1'),
(NULL, 'Display multiple burndowns per page', 'Adapt PHP and JavaScript', NULL, '3', '1', NULL, '1'),
(NULL, 'Research Bootstrap Login', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Implement a simple login system', NULL, NULL, '3', '1', NULL, '1'),
(NULL, 'Develop JavaScript to make use of notifications - Graphs', 'Be able to click on the graph and obtain information', NULL, '3', '1', NULL, '1'),
(NULL, 'Develop JavaScript to make use of notifications - Daashboard', 'Be able to click on the graph and obtain information', NULL, '3', '1', NULL, '1'),
(NULL, 'Create social media accounts', 'Create Zeus Agile Management Twitter, Facebook, Google + and LinkedIn accounts', NULL, NULL, '2', '2', '1'),
(NULL, 'Product Stationary', 'Decide on colours and requirements for branded items?*is that what you mean here?', NULL, '3', '1', NULL, '1'),
(NULL, 'Advertising banners for websites', 'decide on format, content, colour for standard advertising banners', NULL, '2', '1', NULL, '1'),
(NULL, 'Comex Stand', 'Decide on content to present, physical advertising and promotion materials, clothing etc.', NULL, '2', '1', NULL, '1');